src/objects/Beacon__c.object
<CustomObject>
    <fields>
        <fullName>Identifier__c</fullName>
        <externalId>true</externalId>
        <label>Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Major</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minor__c</fullName>
        <label>Minor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uuid__c</fullName>
        <label>Uuid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Beacon</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Beacon</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beacons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mobile_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entered Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exited Region</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Beacon__c</fullName>
        <label>Beacon</label>
        <referenceTo>Beacon__c</referenceTo>
        <relationshipLabel>Mobile Activities</relationshipLabel>
        <relationshipName>Mobile_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <label>ContactId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mobile Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Mobile Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SalesforceBeaconDemoController_v2_0_0.cls
@RestResource(urlMapping='/locationOpps/v2.0.0/*')
global with sharing class SalesforceBeaconDemoController_v2_0_0 {

    @HttpGet
    global static Opportunity getOpportunities() {
        String contactId = RestContext.request.params.get('contactId');
        String beaconIdentifier = RestContext.request.params.get('identifier');
        String beaconUuid = RestContext.request.params.get('uuid');
        String beaconMajor = RestContext.request.params.get('major');
        String beaconMinor = RestContext.request.params.get('minor');        
        String type = RestContext.request.params.get('type');
        list<OpportunityContactRole> ocr = [SELECT Id, Contactid, OpportunityId FROM OpportunityContactRole WHERE ContactId = :contactId LIMIT 1];
        if (!ocr.isEmpty()){
        	list<Opportunity> opp = [SELECT Id, Name, Description, StageName FROM Opportunity WHERE Id = :ocr[0].OpportunityId AND StageName != 'Closed Won' AND StageName != 'Closed Lost' LIMIT 1];
        	if (!opp.isEmpty()){
        		if (type == 'entered')
        		{
        			// Insert mobile activity & beacon info if necessary
	        		Beacon__c matchingBeacon = new Beacon__c(Identifier__c = beaconIdentifier, Uuid__c = beaconUuid, Major__c = beaconMajor, Minor__c = beaconMinor);
	        		Mobile_Activity__c newMobileActivity = new Mobile_Activity__c(ContactId__c = contactId, Beacon__r = new Beacon__c(Identifier__c = beaconIdentifier), Activity_Type__c = (type == 'entered') ? 'Entered Region' : 'Exited Region');
	        		upsert matchingBeacon;
	        		insert newMobileActivity;
        		}
        		return opp[0];
        	}
        }
        return null;
        
	}

}